/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author ameya
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private CustomerDirectory customerDirectory;
    private Customer customer;
    
    /**
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     * @param ecosystem
     * @param customerdirectory
     */


    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization Organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = business;
        this.customerDirectory = business.getCustomerdirectory();
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        for (Customer c : customerDirectory.getCustomerDir()){
            if(c.getUsername().equalsIgnoreCase(account.getUsername())){
                this.customer = c;
            }
        }
        ArrayList<Network> networklist = ecosystem.getNetworkList();
        
        valueLabel.setText(account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jSplitPane1 = new javax.swing.JSplitPane();
                jPanel2 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                valueLabel = new javax.swing.JLabel();
                enterpriseLabel = new javax.swing.JLabel();
                btnEateriespanel = new javax.swing.JButton();
                btnHouseholdServices = new javax.swing.JButton();
                btnyourorders = new javax.swing.JButton();
                lblorder = new javax.swing.JLabel();
                btnEssentials = new javax.swing.JButton();
                btnRetail = new javax.swing.JButton();

                setBackground(new java.awt.Color(255, 255, 255));

                jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
                jSplitPane1.setDividerLocation(0);
                jSplitPane1.setDividerSize(0);

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                jSplitPane1.setLeftComponent(jPanel2);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/userImageOpaque.png"))); // NOI18N

                valueLabel.setForeground(new java.awt.Color(0, 102, 255));
                valueLabel.setText("<value>");

                enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                enterpriseLabel.setForeground(new java.awt.Color(0, 102, 255));
                enterpriseLabel.setText("Hi");

                btnEateriespanel.setBackground(new java.awt.Color(0, 102, 204));
                btnEateriespanel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnEateriespanel.setText("Eateries");
                btnEateriespanel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEateriespanelActionPerformed(evt);
                        }
                });

                btnHouseholdServices.setBackground(new java.awt.Color(0, 102, 204));
                btnHouseholdServices.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnHouseholdServices.setText("Household Services");
                btnHouseholdServices.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHouseholdServicesActionPerformed(evt);
                        }
                });

                btnyourorders.setBackground(new java.awt.Color(0, 102, 204));
                btnyourorders.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnyourorders.setText("Your Orders");
                btnyourorders.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnyourordersActionPerformed(evt);
                        }
                });

                lblorder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                lblorder.setForeground(new java.awt.Color(0, 102, 255));
                lblorder.setText("What would you like to buy today?");

                btnEssentials.setBackground(new java.awt.Color(0, 102, 204));
                btnEssentials.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnEssentials.setText("Essentials");
                btnEssentials.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEssentialsActionPerformed(evt);
                        }
                });

                btnRetail.setBackground(new java.awt.Color(0, 102, 204));
                btnRetail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnRetail.setText("Retail");
                btnRetail.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRetailActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(enterpriseLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(valueLabel))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(135, 135, 135)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(btnHouseholdServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnEateriespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnRetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnEssentials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnyourorders, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(116, 116, 116)
                                                        .addComponent(lblorder)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );

                jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEateriespanel, btnEssentials, btnHouseholdServices, btnRetail, btnyourorders});

                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(valueLabel)
                                                .addComponent(enterpriseLabel))
                                        .addGap(8, 8, 8)
                                        .addComponent(lblorder, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(btnEateriespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnHouseholdServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnRetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnEssentials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnyourorders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(89, 89, 89)))
                );

                jSplitPane1.setRightComponent(jPanel1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSplitPane1)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSplitPane1)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnEateriespanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEateriespanelActionPerformed
            // TODO add your handling code here:
            EateriesJPanel eateriesJPanel = new EateriesJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", eateriesJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }//GEN-LAST:event_btnEateriespanelActionPerformed

        private void btnHouseholdServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseholdServicesActionPerformed
            // TODO add your handling code here:
            ServicesJPanel servicesJPanel = new ServicesJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", servicesJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }//GEN-LAST:event_btnHouseholdServicesActionPerformed

        private void btnEssentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEssentialsActionPerformed
            // TODO add your handling code here:
            EssentialsJPanel essentialsJPanel = new EssentialsJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", essentialsJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
		
        }//GEN-LAST:event_btnEssentialsActionPerformed

        private void btnRetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailActionPerformed
            // TODO add your handling code here:
            RetailJPanel RetailJPanel = new RetailJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", RetailJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }//GEN-LAST:event_btnRetailActionPerformed

        private void btnyourordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyourordersActionPerformed
            // TODO add your handling code here:
            YourOrdersJPanel yourordersJPanel = new YourOrdersJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("yourordersJPanel", yourordersJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);	
        }//GEN-LAST:event_btnyourordersActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnEateriespanel;
        private javax.swing.JButton btnEssentials;
        private javax.swing.JButton btnHouseholdServices;
        private javax.swing.JButton btnRetail;
        private javax.swing.JButton btnyourorders;
        private javax.swing.JLabel enterpriseLabel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JLabel lblorder;
        private javax.swing.JLabel valueLabel;
        // End of variables declaration//GEN-END:variables
}
