/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerRole;

import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ameya
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private CustomerDirectory customerDirectory;
    /**
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     * @param ecosystem
     * @param customerdirectory
     */


    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization Organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = business;
        this.customerDirectory = business.getCustomerdirectory();
        this.account = account;
        this.organization = Organization;
        this.enterprise = enterprise;
        valueLabel.setText(account.getUsername());
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jSplitPane1 = new javax.swing.JSplitPane();
                jPanel1 = new javax.swing.JPanel();
                valueLabel = new javax.swing.JLabel();
                enterpriseLabel = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                btnEateriespanel = new javax.swing.JButton();
                btnHouseholdServices = new javax.swing.JButton();
                btnRetail = new javax.swing.JButton();
                btnEssentials = new javax.swing.JButton();
                lblorder = new javax.swing.JLabel();
                btnyourorders = new javax.swing.JButton();
                btntrackorders = new javax.swing.JButton();

                jSplitPane1.setDividerLocation(200);

                valueLabel.setText("<value>");

                enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                enterpriseLabel.setText("Hi");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(165, Short.MAX_VALUE)
                                .addComponent(enterpriseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valueLabel)
                                .addGap(161, 161, 161))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(valueLabel)
                                        .addComponent(enterpriseLabel))
                                .addContainerGap(417, Short.MAX_VALUE))
                );

                jSplitPane1.setRightComponent(jPanel1);

                btnEateriespanel.setText("Eateries");
                btnEateriespanel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEateriespanelActionPerformed(evt);
                        }
                });

                btnHouseholdServices.setText("Household Services");
                btnHouseholdServices.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHouseholdServicesActionPerformed(evt);
                        }
                });

                btnRetail.setText("Retail");
                btnRetail.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRetailActionPerformed(evt);
                        }
                });

                btnEssentials.setText("Essentials");
                btnEssentials.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEssentialsActionPerformed(evt);
                        }
                });

                lblorder.setText("What would you like to buy today?");

                btnyourorders.setText("Your Orders");
                btnyourorders.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnyourordersActionPerformed(evt);
                        }
                });

                btntrackorders.setText("Track Your Orders");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(lblorder))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(btnHouseholdServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnEateriespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnRetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnEssentials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnyourorders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(btntrackorders))))
                                .addContainerGap(11, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblorder)
                                .addGap(37, 37, 37)
                                .addComponent(btnEateriespanel)
                                .addGap(28, 28, 28)
                                .addComponent(btnHouseholdServices)
                                .addGap(33, 33, 33)
                                .addComponent(btnRetail)
                                .addGap(33, 33, 33)
                                .addComponent(btnEssentials)
                                .addGap(30, 30, 30)
                                .addComponent(btnyourorders)
                                .addGap(26, 26, 26)
                                .addComponent(btntrackorders)
                                .addContainerGap(83, Short.MAX_VALUE))
                );

                jSplitPane1.setLeftComponent(jPanel2);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSplitPane1)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSplitPane1)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnEateriespanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEateriespanelActionPerformed
                // TODO add your handling code here:
		EateriesJPanel eateriesJPanel = new EateriesJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("eateriesJPanel", eateriesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
		
		
        }//GEN-LAST:event_btnEateriespanelActionPerformed

        private void btnHouseholdServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseholdServicesActionPerformed
                // TODO add your handling code here:
		ServicesJPanel servicesJPanel = new ServicesJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("eateriesJPanel", servicesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }//GEN-LAST:event_btnHouseholdServicesActionPerformed

        private void btnEssentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEssentialsActionPerformed
                // TODO add your handling code here:
		EssentialsJPanel essentialsJPanel = new EssentialsJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("eateriesJPanel", essentialsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
		
        }//GEN-LAST:event_btnEssentialsActionPerformed

        private void btnRetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailActionPerformed
                // TODO add your handling code here:
		RetailJPanel RetailJPanel = new RetailJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("eateriesJPanel", RetailJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }//GEN-LAST:event_btnRetailActionPerformed

        private void btnyourordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyourordersActionPerformed
                // TODO add your handling code here:
		YourOrdersJPanel yourordersJPanel = new YourOrdersJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("eateriesJPanel", yourordersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
		
        }//GEN-LAST:event_btnyourordersActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnEateriespanel;
        private javax.swing.JButton btnEssentials;
        private javax.swing.JButton btnHouseholdServices;
        private javax.swing.JButton btnRetail;
        private javax.swing.JButton btntrackorders;
        private javax.swing.JButton btnyourorders;
        private javax.swing.JLabel enterpriseLabel;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JLabel lblorder;
        private javax.swing.JLabel valueLabel;
        // End of variables declaration//GEN-END:variables
}
