/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author ameya
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private CustomerDirectory customerDirectory;
    private Customer customer;
    
    /**
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     * @param ecosystem
     * @param customerdirectory
     */


    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization Organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = business;
        this.customerDirectory = business.getCustomerdirectory();
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        for (Customer c : customerDirectory.getCustomerDir()){
            if(c.getUsername().equalsIgnoreCase(account.getUsername())){
                this.customer = c;
            }
        }
        ArrayList<Network> networklist = ecosystem.getNetworkList();
        
        valueLabel.setText(account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jSplitPane1 = new javax.swing.JSplitPane();
                jPanel2 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                valueLabel = new javax.swing.JLabel();
                enterpriseLabel = new javax.swing.JLabel();
                btnEateriespanel = new javax.swing.JButton();
                btnHouseholdServices = new javax.swing.JButton();
                btnyourorders = new javax.swing.JButton();
                lblorder = new javax.swing.JLabel();
                btnEssentials = new javax.swing.JButton();
                btnRetail = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 255, 255));

                jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
                jSplitPane1.setDividerLocation(0);
                jSplitPane1.setDividerSize(0);

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                jSplitPane1.setLeftComponent(jPanel2);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                valueLabel.setForeground(new java.awt.Color(0, 102, 255));
                valueLabel.setText("<value>");
                jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

                enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                enterpriseLabel.setForeground(new java.awt.Color(0, 102, 255));
                enterpriseLabel.setText("Hi");
                jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

                btnEateriespanel.setBackground(new java.awt.Color(0, 102, 204));
                btnEateriespanel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnEateriespanel.setForeground(new java.awt.Color(255, 255, 255));
                btnEateriespanel.setText("Eateries");
                btnEateriespanel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEateriespanelActionPerformed(evt);
                        }
                });
                jPanel1.add(btnEateriespanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 149, 30));

                btnHouseholdServices.setBackground(new java.awt.Color(0, 102, 204));
                btnHouseholdServices.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnHouseholdServices.setForeground(new java.awt.Color(255, 255, 255));
                btnHouseholdServices.setText("Services");
                btnHouseholdServices.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHouseholdServicesActionPerformed(evt);
                        }
                });
                jPanel1.add(btnHouseholdServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 150, 30));

                btnyourorders.setBackground(new java.awt.Color(0, 102, 204));
                btnyourorders.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnyourorders.setForeground(new java.awt.Color(255, 255, 255));
                btnyourorders.setText("Your Orders");
                btnyourorders.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnyourordersActionPerformed(evt);
                        }
                });
                jPanel1.add(btnyourorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 149, 30));

                lblorder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                lblorder.setForeground(new java.awt.Color(0, 102, 255));
                lblorder.setText("What would you like to buy today?");
                jPanel1.add(lblorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 61));

                btnEssentials.setBackground(new java.awt.Color(0, 102, 204));
                btnEssentials.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnEssentials.setForeground(new java.awt.Color(255, 255, 255));
                btnEssentials.setText("Essentials");
                btnEssentials.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEssentialsActionPerformed(evt);
                        }
                });
                jPanel1.add(btnEssentials, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 149, 30));

                btnRetail.setBackground(new java.awt.Color(0, 102, 204));
                btnRetail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnRetail.setForeground(new java.awt.Color(255, 255, 255));
                btnRetail.setText("Retail");
                btnRetail.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRetailActionPerformed(evt);
                        }
                });
                jPanel1.add(btnRetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 149, 30));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/userImageOpaque.png"))); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 660, 480));

                jSplitPane1.setRightComponent(jPanel1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSplitPane1)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSplitPane1)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnEateriespanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEateriespanelActionPerformed
            // TODO add your handling code here:
            
            EateriesJPanel eateriesJPanel = new EateriesJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", eateriesJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }//GEN-LAST:event_btnEateriespanelActionPerformed

        private void btnHouseholdServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseholdServicesActionPerformed
            // TODO add your handling code here:
            ServicesJPanel servicesJPanel = new ServicesJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", servicesJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }//GEN-LAST:event_btnHouseholdServicesActionPerformed

        private void btnEssentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEssentialsActionPerformed
            // TODO add your handling code here:
            EssentialsJPanel essentialsJPanel = new EssentialsJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", essentialsJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
		
        }//GEN-LAST:event_btnEssentialsActionPerformed

        private void btnRetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailActionPerformed
            // TODO add your handling code here:
            RetailJPanel RetailJPanel = new RetailJPanel(userProcessContainer, ecosystem, customer);
            userProcessContainer.add("eateriesJPanel", RetailJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }//GEN-LAST:event_btnRetailActionPerformed

        private void btnyourordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyourordersActionPerformed
            // TODO add your handling code here:
            YourOrdersJPanel yourordersJPanel = new YourOrdersJPanel(userProcessContainer, ecosystem, customer, enterprise);
            userProcessContainer.add("yourordersJPanel", yourordersJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);	
        }//GEN-LAST:event_btnyourordersActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnEateriespanel;
        private javax.swing.JButton btnEssentials;
        private javax.swing.JButton btnHouseholdServices;
        private javax.swing.JButton btnRetail;
        private javax.swing.JButton btnyourorders;
        private javax.swing.JLabel enterpriseLabel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JLabel lblorder;
        private javax.swing.JLabel valueLabel;
        // End of variables declaration//GEN-END:variables
}
