/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bidar
 */
public class EateriesJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form EateriesJPanel
	 */
	private JPanel userProcessContainer;
        private EcoSystem ecosystem;
        private Customer customer;
        
	public EateriesJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Customer customer) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.ecosystem = ecosystem;
            this.customer = customer;
            populateTable();
            
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                eateriesJTable = new javax.swing.JTable();
                btnMenuDetails = new javax.swing.JButton();
                btnback = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 255, 255));

                eateriesJTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null},
                                {null, null, null, null, null}
                        },
                        new String [] {
                                "Restaurant Name", "Contact Number", "Address", "City", "ZipCode"
                        }
                ));
                jScrollPane1.setViewportView(eateriesJTable);

                btnMenuDetails.setBackground(new java.awt.Color(0, 102, 204));
                btnMenuDetails.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
                btnMenuDetails.setForeground(new java.awt.Color(255, 255, 255));
                btnMenuDetails.setText("View Menu Details");
                btnMenuDetails.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMenuDetailsActionPerformed(evt);
                        }
                });

                btnback.setBackground(new java.awt.Color(255, 255, 255));
                btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/93634-2.png"))); // NOI18N
                btnback.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnbackActionPerformed(evt);
                        }
                });

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/dishes-297268_1280 (1).png"))); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(24, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnMenuDetails)
                                .addGap(327, 327, 327))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnMenuDetails)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
            // TODO add your handling code here:
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
//            CustomerWorkAreaJPanel custAreajp = (CustomerWorkAreaJPanel) component;
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }//GEN-LAST:event_btnbackActionPerformed

    private void btnMenuDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = eateriesJTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String enterpriseName = eateriesJTable.getValueAt(selectedRow, 0).toString();
        Enterprise enterprise = null;
        for(Network n: ecosystem.getNetworkList()){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e.getEnterpriseType().toString().equals("Eateries")){
                        if(e.getName().equalsIgnoreCase(enterpriseName)){
                            enterprise = e;
                        }
                    }
                }
            }
        
        EateriesOrderJPanel eateriesorderJPanel = new EateriesOrderJPanel(userProcessContainer, enterprise, customer);
        userProcessContainer.add("eateriesorderJPanel", eateriesorderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMenuDetailsActionPerformed

        private void populateTable() {
            DefaultTableModel model = (DefaultTableModel) eateriesJTable.getModel();
            model.setRowCount(0);
            for(Network n: ecosystem.getNetworkList()){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e.getEnterpriseType().toString().equals("Eateries")){
                        if(e.getZipcode() == customer.getZipcode()){
                            System.out.println("Enterprise Name :" + e.getName());
                            Object[] row = new Object[5];
                            row[0] = e.getName();
                            row[1] = e.getPhone();
                            row[2] = e.getStreetaddress();
                            row[3] = e.getCity();
                            row[4] = e.getZipcode();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnMenuDetails;
        private javax.swing.JButton btnback;
        private javax.swing.JTable eateriesJTable;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables

    
}
