/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerRole;

<<<<<<< Updated upstream
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
=======
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
>>>>>>> Stashed changes

/**
 *
 * @author bidar
 */
public class EssentialsJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form EssentialsJPanel
	 */
	private JPanel userProcessContainer;
        private EcoSystem ecosystem;
<<<<<<< Updated upstream
	public EssentialsJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
		this.userProcessContainer = userProcessContainer;
            this.ecosystem = ecosystem;
=======
        private Customer customer;
	public EssentialsJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Customer customer) {
>>>>>>> Stashed changes
		initComponents();
                this.userProcessContainer = userProcessContainer;
                this.ecosystem = ecosystem;
                this.customer = customer;
                populateTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
<<<<<<< Updated upstream
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                lblSelectCategory = new javax.swing.JLabel();
                lblAvailableStores = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblStoreDetails = new javax.swing.JTable();
                btnConfirmOrder = new javax.swing.JButton();
                backJButton = new javax.swing.JButton();

                lblTitle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
                lblTitle.setText("Please select required services from below");

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fresh Vegetables and Fruits", "Dairy Products", "Groceries", "Pharmacy" }));

                lblSelectCategory.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
                lblSelectCategory.setText("Select Category");

                lblAvailableStores.setText("Below are the nearest local services available for you   . . ");

                tblStoreDetails.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Store Name", "Contact Number", "Address", "Street Address", "City", "ZipCode"
                        }
                ));
                jScrollPane1.setViewportView(tblStoreDetails);

                btnConfirmOrder.setText("View Details");

                backJButton.setText("<<Back");
                backJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                backJButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblSelectCategory)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblAvailableStores)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(lblTitle)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(151, 151, 151)
                                                .addComponent(btnConfirmOrder))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(backJButton)))
                                .addGap(0, 402, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblTitle)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSelectCategory)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvailableStores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(btnConfirmOrder)
                                .addGap(18, 18, 18)
                                .addComponent(backJButton)
                                .addContainerGap(247, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel custAreajp = (CustomerWorkAreaJPanel) component;
        

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }//GEN-LAST:event_backJButtonActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton backJButton;
        private javax.swing.JButton btnConfirmOrder;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblAvailableStores;
        private javax.swing.JLabel lblSelectCategory;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JTable tblStoreDetails;
        // End of variables declaration//GEN-END:variables
=======
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblSelectCategory = new javax.swing.JLabel();
        lblAvailableStores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        essentialsJTable = new javax.swing.JTable();
        btnMenuDetails = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTitle.setText("Please select required services from below");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fresh Vegetables and Fruits", "Dairy Products", "Groceries", "Pharmacy" }));

        lblSelectCategory.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblSelectCategory.setText("Select Category");

        lblAvailableStores.setText("Below are the nearest local services available for you   . . ");

        essentialsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store Name", "Contact Number", "Street Address", "City", "ZipCode"
            }
        ));
        jScrollPane1.setViewportView(essentialsJTable);

        btnMenuDetails.setText("View Details");
        btnMenuDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDetailsActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSelectCategory)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAvailableStores)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnMenuDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addGap(0, 402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCategory)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvailableStores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnMenuDetails)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
//            CustomerWorkAreaJPanel custAreajp = (CustomerWorkAreaJPanel) component;
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }//GEN-LAST:event_backJButtonActionPerformed

    private void btnMenuDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = essentialsJTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String enterpriseName = essentialsJTable.getValueAt(selectedRow, 0).toString();
        Enterprise enterprise = null;
        for(Network n: ecosystem.getNetworkList()){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e.getEnterpriseType().toString().equals("Essentials")){
                        if(e.getName().equalsIgnoreCase(enterpriseName)){
                            enterprise = e;
                        }
                    }
                }
            }
        
        EssentialsOrderJPanel essentialsorderJPanel = new EssentialsOrderJPanel(userProcessContainer, enterprise, customer);
        userProcessContainer.add("essentialsorderJPanel", essentialsorderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMenuDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnMenuDetails;
    private javax.swing.JTable essentialsJTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailableStores;
    private javax.swing.JLabel lblSelectCategory;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) essentialsJTable.getModel();
            model.setRowCount(0);
            for(Network n: ecosystem.getNetworkList()){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e.getEnterpriseType().toString().equals("Essentials")){
                        if(e.getZipcode() == customer.getZipcode()){
                            System.out.println("Enterprise Name :" + e.getName());
                            Object[] row = new Object[5];
                            row[0] = e.getName();
                            row[1] = e.getPhone();
                            row[2] = e.getStreetaddress();
                            row[3] = e.getCity();
                            row[4] = e.getZipcode();
                            model.addRow(row);
                        }
                    }
                }
            }
    }
>>>>>>> Stashed changes
}
