/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.WholesaleRole;

import Business.Enterprise.Enterprise;
import Business.ItemCatalogue.Items;
import Business.ItemCatalogue.ItemsDirectory;
import Business.Orders.Orders;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bidar
 */
public class ViewOrdersJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ViewOrdersJPanel
	 */
        private Enterprise enterprise;
        private JPanel userProcessContainer;
        private Organization organization;
        private ItemsDirectory itemsdir;
        private ArrayList<Orders> orders;
        private OrganizationDirectory orgdir;
        
	public ViewOrdersJPanel(JPanel userProcessContainer, Organization organization, Enterprise enterprise, ItemsDirectory itemsdir) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.enterprise = enterprise;
            this.organization = organization;
            this.orgdir = enterprise.getOrganizationDirectory();
            this.orders = organization.getOrders();
            this.itemsdir = itemsdir;
            populateTable();
            populateTransportTable();
            for(Organization o : orgdir.getOrganizationList()){
                if(o.getType().equals("Transport")){
                    System.out.println("Organization Name : " + o.getName());
                    System.out.println("Organization Type : " + o.getType());
                }
            }
            
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane5 = new javax.swing.JScrollPane();
                orderJTable = new javax.swing.JTable();
                jTextField1 = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                btnAssignTransport = new javax.swing.JButton();
                btnback = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                transportJTable = new javax.swing.JTable();

                setBackground(new java.awt.Color(255, 255, 255));

                orderJTable.setForeground(new java.awt.Color(0, 102, 204));
                orderJTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Order ID", "Store Name", "Item Name", "Quantity", "Description", "Price"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                true, true, false, false, false, true
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane5.setViewportView(orderJTable);

                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField1ActionPerformed(evt);
                        }
                });

                jLabel1.setForeground(new java.awt.Color(0, 102, 204));
                jLabel1.setText("Total Amount");

                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/file_light-07-512-2.png"))); // NOI18N
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                btnAssignTransport.setBackground(new java.awt.Color(0, 102, 204));
                btnAssignTransport.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
                btnAssignTransport.setForeground(new java.awt.Color(255, 255, 255));
                btnAssignTransport.setText("Assign to Transport Service");
                btnAssignTransport.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAssignTransportActionPerformed(evt);
                        }
                });

                btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/93634-2.png"))); // NOI18N
                btnback.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnbackActionPerformed(evt);
                        }
                });

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/wholesalersicon2 (1).png"))); // NOI18N

                transportJTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Name", "Email Address", "Phone", "User Name"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, true, true, true
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane2.setViewportView(transportJTable);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 6, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAssignTransport)
                                .addGap(188, 188, 188))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAssignTransport)
                                .addContainerGap(154, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextField1ActionPerformed

        private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
            // TODO add your handling code here:
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
//            CustomerWorkAreaJPanel custAreajp = (CustomerWorkAreaJPanel) component;
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }//GEN-LAST:event_btnbackActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
		JOptionPane.showMessageDialog(jButton1, "Order Confirmed!");
        }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAssignTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTransportActionPerformed
        // TODO add your handling code here:
        int selectedOrderRow = orderJTable.getSelectedRow();
        if(selectedOrderRow<0){
            JOptionPane.showMessageDialog(null,"Select an order","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        int selectedDeliveryRow = transportJTable.getSelectedRow();
        if(selectedDeliveryRow<0){
            JOptionPane.showMessageDialog(null,"Select a deliveryman","Warning",JOptionPane.WARNING_MESSAGE);
        }
        int orderID = (int) orderJTable.getValueAt(selectedOrderRow, 0);
            Orders order = null;
            
        for(Orders o : organization.getOrders()){
            if(o.getOrderID() == orderID){
                order = o;
            }
        }
        System.out.println("Order ID :" + order.getOrderID());
        
        String username = (String) transportJTable.getValueAt(selectedDeliveryRow, 3);
        for(Organization org : orgdir.getOrganizationList()){
                if(org.getType().equals("Transport")){
                    for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
                        if(ua.getUsername().equalsIgnoreCase(username)){
                            order.setStatus("Assigned");
                            order.setDeliveryManName(org.getName());
                            order.setDeliveryPhone(org.getPhone());
                            if(enterprise.getInventoryOrderList() != null){
                                enterprise.getInventoryOrderList().add(order);
				JOptionPane.showMessageDialog(jButton1,"Transport service assigned");
                            }
                            else{
                                enterprise.newInvetoryOrdersList();
                                enterprise.getInventoryOrderList().add(order);
				JOptionPane.showMessageDialog(jButton1,"Transport service assigned");
                                for(Orders o1 : enterprise.getInventoryOrderList()){
                                    System.out.println("Order ID:" + o1.getOrderID());
                                    System.out.println("Order Contents :\n");
                                    for(Items i: o1.getOrderlist()){
                                        System.out.println("Item Name :" + i.getName());
                                    }
                                }
                            }
                        }
                    }
                }
            }
    }//GEN-LAST:event_btnAssignTransportActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAssignTransport;
        private javax.swing.JButton btnback;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTable orderJTable;
        private javax.swing.JTable transportJTable;
        // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) orderJTable.getModel();
        model.setRowCount(0);
        for(Orders o : orders){
            for(Items i : o.getOrderlist()){
                Object[] row = new Object[6];
                row[0] = o.getOrderID();
                row[1] = enterprise.getName();
                row[2] = i.getName();
                row[3] = i.getQuantity();
                row[4] = i.getDesc();
                row[5] = i.getPrice();
                model.addRow(row);
            }
        }
    }

    private void populateTransportTable() {
        DefaultTableModel model = (DefaultTableModel) transportJTable.getModel();
        model.setRowCount(0);
        for(Organization o : orgdir.getOrganizationList()){
            if(o.getType().equals("Transport")){
                for(UserAccount ua : o.getUserAccountDirectory().getUserAccountList()){
                    Object[] row = new Object[4]; 
                    row[0] = o.getName();
                    row[1] = o.getEmail();
                    row[2] = o.getPhone();
                    row[3] = ua.getUsername();
                    model.addRow(row);   
                }
            }
        }
    }
}
