/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CleaningRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ServiceWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ameya
 */
public class CleaningWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CleaningWorkAreaJPanel
     */
    private Enterprise enterprise;
    private JPanel userProcessContainer;
    private Organization organization;
    private EcoSystem business;
    private UserAccount account;
    public CleaningWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                enterpriseLabel = new javax.swing.JLabel();
                valueLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                requestJTable = new javax.swing.JTable();
                btnWorking = new javax.swing.JButton();
                btnRefresh = new javax.swing.JButton();
                btnCompleted = new javax.swing.JButton();

                setBackground(new java.awt.Color(255, 255, 255));

                enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                enterpriseLabel.setForeground(new java.awt.Color(0, 102, 204));
                enterpriseLabel.setText("Hi");

                valueLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                valueLabel.setForeground(new java.awt.Color(0, 102, 204));
                valueLabel.setText("<value>");

                requestJTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Request ID", "Customer Name", "Customer Address", "Message", "Status"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(requestJTable);

                btnWorking.setBackground(new java.awt.Color(0, 102, 204));
                btnWorking.setForeground(new java.awt.Color(255, 255, 255));
                btnWorking.setText("Working");
                btnWorking.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnWorkingActionPerformed(evt);
                        }
                });

                btnRefresh.setBackground(new java.awt.Color(0, 102, 204));
                btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
                btnRefresh.setText("Refresh");
                btnRefresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRefreshActionPerformed(evt);
                        }
                });

                btnCompleted.setBackground(new java.awt.Color(0, 102, 204));
                btnCompleted.setForeground(new java.awt.Color(255, 255, 255));
                btnCompleted.setText("Completed");
                btnCompleted.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCompletedActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(enterpriseLabel)
                                                .addGap(6, 6, 6)
                                                .addComponent(valueLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(btnWorking, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(62, 62, 62))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(enterpriseLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(valueLabel)))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRefresh)
                                        .addComponent(btnCompleted)
                                        .addComponent(btnWorking)))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnWorkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkingActionPerformed
            int selectedOrderRow = requestJTable.getSelectedRow();
            if(selectedOrderRow<0){
                JOptionPane.showMessageDialog(null,"Select a request","Warning",JOptionPane.WARNING_MESSAGE);
            }
            int requestID = (int) requestJTable.getValueAt(selectedOrderRow, 0);
            for(ServiceWorkRequest sw: enterprise.getRequestList()){
                if(sw.getRequestID() == requestID){
                    sw.setStatus("Working");
		    JOptionPane.showMessageDialog(btnCompleted, "Updated status to working");
                }
            }
            populateTable();
        }//GEN-LAST:event_btnWorkingActionPerformed

        private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
            populateTable();
        }//GEN-LAST:event_btnRefreshActionPerformed

        private void btnCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletedActionPerformed
            int selectedOrderRow = requestJTable.getSelectedRow();
            if(selectedOrderRow<0){
                JOptionPane.showMessageDialog(null,"Select a request","Warning",JOptionPane.WARNING_MESSAGE);
            }
            int requestID = (int) requestJTable.getValueAt(selectedOrderRow, 0);
            for(ServiceWorkRequest sw: enterprise.getRequestList()){
                if(sw.getRequestID() == requestID){
                    sw.setStatus("Completed");
		    JOptionPane.showMessageDialog(btnCompleted, "Updated status to Complete");
                }
            }
            populateTable();
        }//GEN-LAST:event_btnCompletedActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCompleted;
        private javax.swing.JButton btnRefresh;
        private javax.swing.JButton btnWorking;
        private javax.swing.JLabel enterpriseLabel;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable requestJTable;
        private javax.swing.JLabel valueLabel;
        // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) requestJTable.getModel();
        model.setRowCount(0);
        for(ServiceWorkRequest sw: enterprise.getRequestList()){
            if(sw.getType().equals("Cleaning")){
                Object[] row = new Object[5];
                row[0] = sw.getRequestID();
                row[1] = sw.getCustomer().getName();
                row[2] = sw.getCustomer().getStreetAddress();
                row[3] = sw.getMessage();
                row[4] = sw.getStatus();
                model.addRow(row);
            }
        }
    }
}
