/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdministrativeRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Enterprise.Enterprise;
import Business.Orders.Orders;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bidar
 */
public class ManageOrdersJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ManageOrdersJPanel
	 */
	private Enterprise enterprise;;
        private JPanel userProcessContainer;
        private CustomerDirectory customerdir;
        private OrganizationDirectory orgdir;
	public ManageOrdersJPanel(JPanel userProcessContainer, Enterprise enterprise) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.enterprise = enterprise;
            this.customerdir = enterprise.getCustomerdirectory();
            this.orgdir = enterprise.getOrganizationDirectory();
            populateOrderTable();
            populateDeliveryMenTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                orderJTable = new javax.swing.JTable();
                btnViewOrder = new javax.swing.JButton();
                btnAssignDeliveryMan = new javax.swing.JButton();
                btnRefresh = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                deliveryJTable = new javax.swing.JTable();

                setBackground(new java.awt.Color(255, 255, 255));

                orderJTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "OrderID", "Customer", "Store Name", "Delivery Location", "Total Amount", "Status"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(orderJTable);

                btnViewOrder.setBackground(new java.awt.Color(0, 102, 204));
                btnViewOrder.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnViewOrder.setForeground(new java.awt.Color(255, 255, 255));
                btnViewOrder.setText("View Order");
                btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnViewOrderActionPerformed(evt);
                        }
                });

                btnAssignDeliveryMan.setBackground(new java.awt.Color(0, 102, 204));
                btnAssignDeliveryMan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnAssignDeliveryMan.setForeground(new java.awt.Color(255, 255, 255));
                btnAssignDeliveryMan.setText("Assign Delivery Man to Order");
                btnAssignDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAssignDeliveryManActionPerformed(evt);
                        }
                });

                btnRefresh.setBackground(new java.awt.Color(0, 102, 204));
                btnRefresh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
                btnRefresh.setText("Refresh");
                btnRefresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRefreshActionPerformed(evt);
                        }
                });

                btnBack.setBackground(new java.awt.Color(255, 255, 255));
                btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Icons/93634-2.png"))); // NOI18N
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 102, 204));
                jLabel1.setText("Orders for your Enterprise");

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 102, 204));
                jLabel2.setText("Available Deliverymen");

                deliveryJTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Name", "Email Address", "Phone", "User Name"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, true, true, true
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane2.setViewportView(deliveryJTable);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(239, 239, 239)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(280, 280, 280)
                                                .addComponent(btnAssignDeliveryMan))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnViewOrder)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnRefresh))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(315, 315, 315)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(52, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnViewOrder)
                                        .addComponent(btnRefresh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAssignDeliveryMan)
                                .addContainerGap(24, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
            // TODO add your handling code here:
            int selectedOrderRow = orderJTable.getSelectedRow();
            if(selectedOrderRow<0){
                JOptionPane.showMessageDialog(null,"Select an order","Warning",JOptionPane.WARNING_MESSAGE);
            }
            int orderID = (int) orderJTable.getValueAt(selectedOrderRow, 0);
            Orders order = null;
            
            for(Orders o : enterprise.getOrders()){
                if(o.getOrderID() == orderID){
                    order = o;
                }
            }
            ViewOrdersJPanel viewordersJPanel = new ViewOrdersJPanel(userProcessContainer, enterprise, order);
            userProcessContainer.add("viewordersJPanel", viewordersJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                
        }//GEN-LAST:event_btnViewOrderActionPerformed

        private void btnAssignDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDeliveryManActionPerformed
            // TODO add your handling code here:
            int selectedOrderRow = orderJTable.getSelectedRow();
            if(selectedOrderRow<0){
                JOptionPane.showMessageDialog(null,"Select an order","Warning",JOptionPane.WARNING_MESSAGE);
            }
            
            int selectedDeliveryRow = deliveryJTable.getSelectedRow();
            if(selectedDeliveryRow<0){
                JOptionPane.showMessageDialog(null,"Select a deliveryman","Warning",JOptionPane.WARNING_MESSAGE);
            }
            
            int orderID = (int) orderJTable.getValueAt(selectedOrderRow, 0);
            Orders order = null;
            
            for(Orders o : enterprise.getOrders()){
                if(o.getOrderID() == orderID){
                    order = o;
                }
            }
            
            String username = (String) deliveryJTable.getValueAt(selectedDeliveryRow, 3);
            for(Organization org : orgdir.getOrganizationList()){
                if(org.getType().equals("Delivery")){
                    for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
                        if(ua.getUsername().equalsIgnoreCase(username)){
                            order.setStatus("Assigned");
                            order.setDeliveryManName(org.getName());
                            order.setDeliveryPhone(org.getPhone());
                            if(enterprise.getDeliveryOrderList() != null){
                                enterprise.getDeliveryOrderList().add(order);
				JOptionPane.showMessageDialog(jScrollPane1, "Delivery Man Assigned");
                            }
                            else{
                                enterprise.newDeliveryOrdersList();
                                enterprise.getDeliveryOrderList().add(order);
				JOptionPane.showMessageDialog(jScrollPane1, "Delivery Man Assigned");
                            }
                        }
                    }
                }
            }
                
        }//GEN-LAST:event_btnAssignDeliveryManActionPerformed

        private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
            // TODO add your handling code here:
            populateOrderTable();
            populateDeliveryMenTable();
                
        }//GEN-LAST:event_btnRefreshActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);                // TODO add your handling code here:userProcessContainer.remove(this);
                
        }//GEN-LAST:event_btnBackActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAssignDeliveryMan;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnRefresh;
        private javax.swing.JButton btnViewOrder;
        private javax.swing.JTable deliveryJTable;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable orderJTable;
        // End of variables declaration//GEN-END:variables

    private void populateOrderTable() {
        DefaultTableModel model = (DefaultTableModel) orderJTable.getModel();
        model.setRowCount(0);
        for(Orders o : enterprise.getOrders()){
            Object[] row = new Object[6]; 
            row[0] = o.getOrderID();
            row[1] = o.getCustomerName();
            row[2] = o.getEnterpriseName();
            row[3] = o.getCustomerAddress();
            row[4] = o.getTotalprice();
            row[5] = o.getStatus();
            model.addRow(row);
        }
    }

    private void populateDeliveryMenTable() {
        DefaultTableModel model = (DefaultTableModel) deliveryJTable.getModel();
        model.setRowCount(0);
        for(Organization o : orgdir.getOrganizationList()){
            if(o.getType().equals("Delivery")){
                for(UserAccount ua : o.getUserAccountDirectory().getUserAccountList()){
                    Object[] row = new Object[4]; 
                    row[0] = o.getName();
                    row[1] = o.getEmail();
                    row[2] = o.getPhone();
                    row[3] = ua.getUsername();
                    model.addRow(row);   
                }
            }

        }
    }
}
